### ISSUE TITLE
add btc support. my compromised wallet is btc

### ISSUE THREAD

**Issue by ayofimihan** [jaredonsolana/Magic-Eden-Airdrop-Compromised-Wallet-Claim-Tool-#1]

**Comment by jaredonsolana** [comment]
working on it

**Comment by jaredonsolana** [comment]
i just added a new repo instead of using this one so people don't get confused. Let me know if you have issues with it, i didn't test it much since I don't have any claims on bitcoin myself.

**Comment by ayofimihan** [comment]
deleted?
